### ISSUE TITLE
Multiprocessing Efficiency 

### ISSUE THREAD

**Issue by jgockley62** [grocsvs/grocsvs#13]
Just got the package up and running with multiprocessing from the docker image. It's working fine, but one note of potential optimization. Is there a way to organize the order in which chunks are run to account for their prospective times?

For example it appears to be ignoring of how many breakpoints it process per-chunk during the _RefineGridSearchBreakpointsStep_ , meaning it runs Chr1.Chr1, Chr2.Chr1, Chr2.Chr2,...
 
So when this process ends I have one processor chugging through ChrY.ChrY which just so happens to have a large amount of breakpoints (177) to process, while my other processors sit idle. Is there a way order these so that the largest will run first and the smallest last to improve resource efficiency and time? 

I apologize in advance if I misunderstand how the package is running.

**Comment by nspies** [comment]
You seem to have grokked how things are working overall, so I'll point you to a few places where you could make some of these adjustments yourself. I'm happy to accept pull requests if you make some optimizations that think are useful.

Before running a stage, it first creates a list of the steps that need to be completed for that stage. It wouldn't be difficult to go in there and change the ordering. For example you could resort the list of chroms here by size before doing the `itertools.product`:

https://github.com/grocsvs/grocsvs/blob/master/src/grocsvs/stages/refine_grid_search_breakpoints.py#L74

You might need a little trial and error to figure out what the best ordering is -- could random be better than by size?

**Comment by jgockley62** [comment]
Awesome thanks!
