### ISSUE TITLE
Errors with memory size

### ISSUE THREAD

**Issue by linwang6** [grocsvs/grocsvs#14]
Hi,
When I set:
    "cluster_settings": {
        "cluster_type": "multiprocessing",
        "processes": 16,
        "cluster_options": {
            "scheduler": "torque",
            "queue": "owners",
            "mem": "48g"
        }
    }
it returns =>> PBS: job killed: vmem 59867090944 exceeded limit 53687091200,

and when I set   "mem": "32g", it also give =>> PBS: job killed: vmem 39766380544 exceeded limit 38654705664, how to fix it? Thanks.

**Comment by nspies** [comment]
Can you give me a few more details:

- is this running on the human genome?
- which step is it failing on?
- what is your library coverage? how many samples are you running at once?
- does the pipeline work on some samples to completion, but not others?

48g of memory should really be enough if you're running on the human genome!

**Comment by linwang6** [comment]
Hi,
1. Human genome.
2. In Window Barcodes step, it failed
3.30x. Just one tumor sample, there is no control sample. Another thing, can I run with two lanes an the same time (those two lanes data is the same tumor sample, sequenced by two times).
4. All not completion.

**Comment by linwang6** [comment]
Hi,
1. Human genome.
2. In Window Barcodes step, it failed
3. 30x. Just one tumor sample.
4. All not completion.
Thanks.

**Comment by linwang6** [comment]
Hi,

  1.  Human genome.
  2.  In Window Barcodes step, it failed
  3.  30x. Just one tumor sample, there is no control sample. Another thing, can I run with two lanes an the same time (those two lanes data is the same tumor sample, sequenced by two times).
  4.  All not completion.

I used the --multiprocessing parameter (processes:16, mem:48g), it will give error, but when I set local parameter, it seems still to be running now, but it has not finished, I don't know whether it will fail or not, it was set up yesterday, it is still running until now. Thanks.

Lin
________________________________

**Comment by nspies** [comment]
Sorry for the slow responses here, I've been out on leave.

When you use the "--multiprocessing" command line option or specify "multiprocessing" in your cluster_settings, the pipeline gets run locally without submitting jobs to the cluster. You should change the cluster_type to "IPCluster", which uses ipython-cluster-helper (a python module) to submit jobs to your cluster.

If you run in multiprocessing, you'll need to provide about 16g of memory *per process*, so if you specify 16 processes, you'll need about 256g of memory.

Please let me know if this fixes your problems. If you're still having problems, please send me the full configuration.json file as well as the complete command line that you're using to launch the jobs from the terminal (you can email this to me if you'd rather). A quick description of your cluster setup would also be useful.

**Comment by linwang6** [comment]
Ok, thanks, I will have a try.

**Comment by linwang6** [comment]
Hi,

There is error again, here is my command line and the configuration.json file

I use run_grocsvs_local.sh script to submit my jobs,

  1.  run_grocsvs_local.sh

       #!/bin/bash

       grocsvs tumor_configuration_local.json

   2. tumor_configuration_local.json



{

    "ref_fasta":"/home/lwang6/bin/grocsvs/refdata-hg19-2.1.0/fasta/genome.fa",

    "bwa_index":"/home/lwang6/bin/Index/genome.fa",

    "blacklists":[

        "/home/lwang6/bin/grocsvs/refdata-hg19-2.1.0/genes/gene_boundaries.bed"

    ],

    "binaries": {

        "bwa": "/home/lwang6/bin/bwa-0.7.15/bwa"

    },

    "samples":{

        "Tumor":[

            {

                "type":"TenXDataset",

                "bam":"/data/lwang6/10X/cell_line/MaMel_27II/Longranger_0013_finished_WithSomatic/outs/phased_possorted_bam.bam",

                "id":"Tumor"

            }

        ]

    },

    "cluster_settings": {

        "cluster_type": "multiprocessing",

        "processes": 6,

        "cluster_options": {

            "scheduler": "torque",

            "queue": "owners",

            "mem": "115g"

        }

    }

}


but there is still error with:

=>> PBS: job killed: vmem 124252106752 exceeded limit 123480309760


so it failed again. Could you help with this, I don't know how to set the processes and mem now. Thanks.

Best wishes,

Lin


________________________________

**Comment by nspies** [comment]
Can you send me the results of the QC and Sample Info steps? These are generated prior to the step that fails, and would indicate if there's a possible reason that your sample is using far more memory than expected.

**Comment by linwang6** [comment]
Sure, here is the QCStep and SampleIfoStep information:

more QCStep

2017-11-02 16:32:11 - -- starting logging QCStep --

2017-11-02 16:32:13 - -> finished running step; time elapsed: 0:00:02.541295

2017-11-02 16:32:13 - -- stopping logging --


more SampleInfoStep.Tumor

2017-11-02 16:23:37 - -- starting logging SampleInfoStep.Tumor --

2017-11-02 16:23:37 - Getting sample info for Tumor

2017-11-02 16:23:37 -  loading fragments...

2017-11-02 16:26:11 - BG Frag Length Distribution: chr1

2017-11-02 16:26:26 - BG Frag Length Distribution: chr2

2017-11-02 16:26:49 - BG Frag Length Distribution: chr3

2017-11-02 16:26:59 - BG Frag Length Distribution: chr4

2017-11-02 16:27:06 - BG Frag Length Distribution: chr5

2017-11-02 16:27:16 - BG Frag Length Distribution: chr6

2017-11-02 16:27:23 - BG Frag Length Distribution: chr7

2017-11-02 16:27:34 - BG Frag Length Distribution: chr8

2017-11-02 16:27:43 - BG Frag Length Distribution: chr9

2017-11-02 16:27:49 - BG Frag Length Distribution: chr10

2017-11-02 16:27:54 - BG Frag Length Distribution: chr11

2017-11-02 16:28:00 - BG Frag Length Distribution: chr12

2017-11-02 16:28:06 - BG Frag Length Distribution: chr13

2017-11-02 16:28:11 - BG Frag Length Distribution: chr14

2017-11-02 16:28:15 - BG Frag Length Distribution: chr15

2017-11-02 16:28:20 - BG Frag Length Distribution: chr16

2017-11-02 16:28:25 - BG Frag Length Distribution: chr17

2017-11-02 16:28:29 - BG Frag Length Distribution: chr18

2017-11-02 16:28:33 - BG Frag Length Distribution: chr19

2017-11-02 16:28:37 - BG Frag Length Distribution: chr20

2017-11-02 16:28:41 - BG Frag Length Distribution: chr21

2017-11-02 16:28:44 - BG Frag Length Distribution: chr22

2017-11-02 16:28:47 - BG Frag Length Distribution: chrX

2017-11-02 16:28:53 - BG Frag Length Distribution: chrY

2017-11-02 16:32:11 - -> finished running step; time elapsed: 0:08:33.289269

2017-11-02 16:32:11 - -- stopping logging --


Thanks.


________________________________

**Comment by linwang6** [comment]
This morning, all seven jobs failed, all because of exceeded memory in SV Candidate regions,

============================== SV Candidate Regions ==============================

300 chunks to run. Starting...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr1.chr1 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr5.chr2 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr7.chr2 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr8.chr6 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr9.chr9 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr11.chr1 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:03 - -- starting logging SVCandidateRegionsStep.Tumor.Tumor.chr12.chr1 --

2017-11-11 06:43:03 - loading...

2017-11-11 06:43:39 - getting SV regions...

2017-11-11 06:43:41 - Using offdiagonal distance of 15 (with window size 10000)

=>> PBS: job killed: vmem 184542662656 exceeded limit 123480309760


The command is :  grocsvs tumor_configuration_local.json

The configuration file is: tumor_configuration_local.json

{

    "ref_fasta":"/home/lwang6/bin/grocsvs/refdata-hg19-2.1.0/fasta/genome.fa",

    "bwa_index":"/home/lwang6/bin/Index/genome.fa",

    "blacklists":[

        "/home/lwang6/bin/grocsvs/refdata-hg19-2.1.0/genes/gene_boundaries.bed"

    ],

    "binaries": {

        "bwa": "/home/lwang6/bin/bwa-0.7.15/bwa"

    },

    "samples":{

        "Tumor":[

            {

                "type":"TenXDataset",

                "bam":"/data/lwang6/10X/cell_line/0003/Longranger_L003_cell3_finished_With.somatic.parameter/outs/phased_possorted_bam.bam",

                "id":"Tumor"

            }

        ]

    },

    "cluster_settings": {

        "cluster_type": "multiprocessing",

        "processes": 7,

        "cluster_options": {

            "scheduler": "torque",

            "queue": "owners",

            "mem": "115g"

        }

    }

}


I have tried many times, how to fix it? Thank you so much.




________________________________

**Comment by nspies** [comment]
I need the *results* from the QC and Sample Info steps (in the results subdirectories) rather than the logs.

I'm still not sure if you've tried setting "cluster_type" to "IPCluster"?

**Comment by linwang6** [comment]
Hi,
I set process with 4, mem with 150gb and cluster_type with multiprocessing, it seems works, but just in the Visualize step it reported 
============================== Visualize ==============================
--> 0 chunks need to be run. Skipping...

** rpy2 not installed correctly; skipping visualization step **

Thanks.

**Comment by nspies** [comment]
Ah, progress! I'm still not sure why your dataset is using so much memory, I'm guessing it has something to do with there being a large number of short fragments (which you could see from the qc reports).

You can re-run grocsvs to produce just the visualizations after installing rpy2 (https://rpy2.bitbucket.io).

**Comment by linwang6** [comment]
Here is the qc_report
Fragment lengths                                                     
 - 10%                                                            251
 - 25%                                                            433
 - 50%                                                         12,012
 - 75%                                                         42,170
 - 90%                                                         83,115
 - 95%                                                        115,012
 - mean                                                        29,120
 - std                                                         40,864
 - N50                                                         73,442
Physical depth (Cf)                                    133.2 +/- 65.5
Read coverage per fragment position (Cr)  0.36 +/- 0.33 (median=0.18)
Good barcodes                                                 975,725

I will have a try to install rpy2 and re-run the grocsvs. 
Another thing, in the MergeGenotypesStep/genotypes.tsv file, blacklist PASS or FAIL, I do not understand it well, PASS means this SV is not near the blacklist (Centromere or Gap), FAIL means the SV is derived from the blacklist?  Thanks.

**Comment by nspies** [comment]
Hrm, you have a somewhat lower fragment length distribution than ideal, but it doesn't look terrible and probably doesn't explain the memory issues. I'm not sure I'll be able to figure out the problem without actually having the data myself to look at. I hope how you've run it now is workable for you for future datasets.

I think you might have mixed up columns in the genotypes.tsv file. The blacklist column should be empty if the event is distant from all blacklisted regions (cen/gap/etc, whatever you provided in your config file) or look something like "SEGDUP,assembly_change,N=3724" if it's near a segmental duplication and a gap and region that changed between human genome builds.

If an event is near a blacklisted region, the quality column will become FAIL.

I recommend, rather than looking at the genotypes file, to use the vcf file produced in the postprocessing step, as there are better headers documenting the output.

**Comment by linwang6** [comment]
Ok, thanks so much.

**Comment by linwang6** [comment]
I checked the vcf file in postprocessing step, the SVTYPEs are all the same 'BND', so there is no classified information for SV, for example DEL, INV, INS and so on, but there is have this information in longranger, here is a line of vcf output from GROCSVS
SVTYPE=BND;MATEID=0:1;EVENT=0. Thanks.

**Comment by linwang6** [comment]
I checked the vcf file in postprocessing step, the SVTYPEs are all the same 'BND', so there is no classified information for SV, for example DEL, INV, INS and so on, but there is this information in longranger, here is a line of vcf output from GROCSVS
SVTYPE=BND;MATEID=0:1;EVENT=0. Thanks.

**Comment by nspies** [comment]
This is correct. If you want to infer the event type, I'd filter to get only small events (say under 100kb) and then look at the relative orientation of the breakpoints. This is not hard, but the emphasis of grocsvs is on large events that are more accurately described as translocations or rearrangements than simple deletions, inversions, etc.

**Comment by linwang6** [comment]
Got it, thanks for your speedy response.
