### ISSUE TITLE
How long it takes for 30X human genome data?

### ISSUE THREAD

**Issue by linwang6** [grocsvs/grocsvs#15]
Hi,
I run grocsvs on human genome data 30X coverage with single process, it took seven days until now, just run the BarcodeOverlapStep. It so slow. But when I run it with multiprocess, it will die because of the memory (45gb memory), which is larger the suggested memory size(16gb), I don't know why? Thanks.

**Comment by nspies** [comment]
Fully parallelized on a cluster, it should take about 24 hours to run. Let's get things running properly on your cluster (see my response in the other issue).
