### ISSUE TITLE
installation issue on centos 6

### ISSUE THREAD

**Issue by rdmorin** [grocsvs/grocsvs#19]
Installation fails if the instructions are followed as written. Workaround is to specify the requirements file explicitly.

```pip install -r requirements.txt```

**Comment by nspies** [comment]
Thanks for explaining how you were able to get the software installed. I will note that the requirements.txt file hasn't been updated since I moved the codebase to be compatible with networkx 2.x and so there may be some runtime errors if you didn't install the latest version of that package. I'll update requirements.txt to reflect this new dependency.

Can you provide some details so that I can update the installation procedure or documentation accordingly?

**Comment by rdmorin** [comment]
The installation was done by a student in the lab @ckrushton. He ran the above command in a new conda environment. 
Details for the environment are below:
# Name                    Version                   Build  Channel
admiral                   0.1                       <pip>
backports-abc             0.5                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py27_0
decorator                 4.3.0                     <pip>
enum34                    1.1.6                     <pip>
freetype                  2.8                  h48caf01_1    BioBuilds
futures                   3.2.0                     <pip>
graphviz                  2.38.0                        0    BioBuilds
h5py                      2.6.0                     <pip>
humanfriendly             4.12                      <pip>
ipykernel                 4.8.2                     <pip>
ipyparallel               6.1.1                     <pip>
ipython                   4.2.1                     <pip>
ipython-cluster-helper    0.5.4                     <pip>
ipython-genutils          0.2.0                     <pip>
jpeg                      9b                   h67a1377_0    BioBuilds
jupyter-client            5.2.3                     <pip>
jupyter-core              4.4.0                     <pip>
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 7.2.0                hdf63c60_3
libgd                     2.2.3                ha7883c6_2    BioBuilds
libpng                    1.6.34               ha6fa132_1    BioBuilds
libstdcxx-ng              7.2.0                hdf63c60_3
libtiff                   4.0.8                h04300b7_0    BioBuilds
monotonic                 1.4                       <pip>
ncurses                   6.0                  h9df7e31_2
netifaces                 0.10.6                    <pip>
networkx                  1.11                      <pip>
networkx                  2.1                       <pip>
numpy                     1.11.2                    <pip>
openssl                   1.0.2o               h20670df_0
pandas                    0.19.2                    <pip>
pathlib2                  2.3.2                     <pip>
pexpect                   4.5.0                     <pip>
pickleshare               0.7.4                     <pip>
pip                       9.0.3                    py27_0
psutil                    5.2.1                     <pip>
ptyprocess                0.5.2                     <pip>
pybedtools                0.7.9                     <pip>
pyfaidx                   0.4.8.2                   <pip>
pygraphviz                1.3.1                    py27_0    bioconda
pysam                     0.10.0                    <pip>
python                    2.7.14              h1571d57_31
python-dateutil           2.7.2                     <pip>
pytz                      2018.4                    <pip>
pyzmq                     17.0.0                    <pip>
readline                  7.0                  ha6073c6_4
scandir                   1.7                       <pip>
scipy                     0.19.0                    <pip>
setuptools                39.0.1                   py27_0
simplegeneric             0.8.1                     <pip>
singledispatch            3.4.0.3                   <pip>
six                       1.11.0                    <pip>
sqlite                    3.23.1               he433501_0
tk                        8.6.7                hc745277_3
tornado                   5.0.2                     <pip>
traitlets                 4.3.2                     <pip>
wheel                     0.31.0                   py27_0
xz                        5.2.3                h5714765_0    BioBuilds
zlib                      1.2.11               ha838bed_2

**Comment by nspies** [comment]
Closing for lack of information. Please reopen if problems persist.
