### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by sgreer77** [grocsvs/grocsvs#2]
I am having some trouble installing GROC-SVs. On a CentOS Linux server, I cloned the grocsvs github repository, however when I run 'pip install .', I receive the following error: 

Could not find a version that satisfies the requirement distribute==0.0 (from ipython-cluster-helper->grocsvs==0.1)

Any advice would be appreciated!

**Comment by nspies** [comment]
Hrm, this sounds like python isn’t installed completely, or you’re using an older version. Maybe make sure that you have python 2.7 and a relatively recent python-pip package installed. Alternatively, can you try “pip install -U pip” and see if upgrading pip fixes the issue?

**Comment by nspies** [comment]
Any updates here? Happy to provide more help if needed. I'd like to close this issue if you got groc-svs working.

**Comment by sgreer77** [comment]
Hi -- sorry I didn't see your message before. Not sure what the issue was but likely something weird with the specific python install I was using. I was able to install grocsvs successfully elsewhere. Thanks!
