### ISSUE TITLE
not a cluster

### ISSUE THREAD

**Issue by nrius** [grocsvs/grocsvs#25]
Hello,
I am running GROC-SV in a server that is not a cluster. I have used "--local" and "--multiprocessing" in the command line and they work, but with the former the process is very slow and with the latter, as it uses all the 48 available CPUs at 100%, the server overloads. I've read this part: "To run in parallel on a single machine, use cluster_type":"multiprocessing" and specify the desired number of processes." but **I am not sure I can use it and if so what I have to do with the rest of the cluster setting of the json file**. I have tried the two following options, but GROC-SV seems to use the last instruction given through the command line. Can you help me?

----------------------------------------
    "cluster_settings": {
        "cluster_type": "multiprocessing",
        "processes": "6"
---------------------------------------
    "cluster_settings": {
        "cluster_type": "multiprocessing",
        "processes": "8",
        "cluster_options": {
            "scheduler": NONE,
            "queue": NONE,
            "mem": NONE
        }

**Comment by nspies** [comment]
The first example you have looks correct to me. If you specify ``multiprocessing`` in the config.json file, you shouldn't specify anything on the command line -- this will override your request to use 6 processes.

As a side-note, I don't expect you'll get great performance with only 6 processors. This could take quite a while to run!

**Comment by nrius** [comment]
I have used the first option (with the missing "}") several times and when I launch it, it uses all the processors in the server until it overloads it. It behaves like it does when I use --multiprocessing on the command line (that I am not using now).

Thanks for the advise, but I am using low numbers of processes to be able to track them when I do htop.
I don't have much experience on this, so any help is appreciated. Thanks!
