### ISSUE TITLE
demux.py  Unable to find barcode_set 'SI-GA-A6'

### ISSUE THREAD

**Issue by linwang6** [grocsvs/grocsvs#5]
python /grocsvs-0.2.5/simple_demux_map/demux.py -s SI-GA-A6=SampleA -s SI-GA-A7=SampleB -b /grocsvs-0.2.5/simple_demux_map/4M-with-alts-february-2016.txt.xz -o Fastq reads_1.fastq.gz reads_2.fastq.gz

Namespace(fastq1='reads_1.fastq.gz', fastq2='reads_2.fastq.gz', gem_barcodes='/grocsvs-0.2.5/simple_demux_map/4M-with-alts-february-2016.txt.xz', outdir='Fastq', sample=['SI-GA-A6=SampleA', 'SI-GA-A7=SampleB'])
Unable to find barcode_set 'SI-GA-A6'
 
Why can't find this barcode_set SI-GA-A6? I checked the _bcs.py file, there is SI-GA-A6 in this file? Can you help with it? Thank you!

**Comment by nspies** [comment]
I have updated the readme for the demux.py script to indicate that you must be in the simple_demux_map directory for it to find the _bcs.py auxiliary file b32049da4599b69f5449f97fbb4a0bc239558237
