### ISSUE TITLE
this requires python2

### ISSUE THREAD

**Issue by gh-ahardin** [grocsvs/grocsvs#6]
Hi, I'm trying to test out your code on Ubuntu 16.04 with python3.5.2 and I'm getting a bunch of issues (print without (), use of basestring) that made me think this is actually a python2 program. Indeed, it works fine with pip2 install ./ but that should be made clear in the requirements. 

Thanks!

**Comment by nspies** [comment]
Thanks for your comment -- I've updated the readme to reflect the lack of py3 support!

**Comment by apteryks** [comment]
I think this issue should be reopened; Python 2 has been obsolete for more than a year now.

**Comment by apteryks** [comment]
Package removed from the Guix collection due to depending on Python 2.  Ping if/when this is fixed!  Thank you.
