### ISSUE TITLE
fatal error: graphviz/cgraph.h: No such file or directory

### ISSUE THREAD

**Issue by simoncchu** [grocsvs/grocsvs#9]
Hi,

I tried to install GROC-SVs on a linux server.  And met this error: "pygraphviz/graphviz_wrap.c:2954:29: fatal error: graphviz/cgraph.h: No such file or directory".

I think graphviz is installed, but because without root access, I installed it locally. Is there a way to set the "include" and "lib" path of graphviz when install GROC-SVs.

Thank you.

**Comment by simoncchu** [comment]
I have solve the issue by installing pygraphviz alone given the path of graphviz: "python setup.py install --include-path=/local_path/graphviz/include --library-path=/local_path/graphviz/lib"

**Comment by nspies** [comment]
Thanks for sharing your solution.

**Comment by mxlian** [comment]
I needed to add graphviz dev package. On ubuntu: `sudo apt install graphviz-dev`

**Comment by austinmw** [comment]
> I needed to add graphviz dev package. On ubuntu: `sudo apt install graphviz-dev`

worked for me with `yum` too.

**Comment by DreigoAgnet** [comment]
> > I needed to add graphviz dev package. On ubuntu: `sudo apt install graphviz-dev`
> 
> worked for me with `yum` too.

Yup. Note: As usual with yum/dnf, it's graphviz-**devel**.
